djangoapp/blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import Index, Page, Post, Created_by, Category, Tag, Search

app_name = 'blog'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('post/<slug:slug>', Post.as_view(), name='post'),
    path('page/<slug:slug>', Page.as_view(), name='page'),
    path('created_by/<int:author_id>/', Created_by.as_view(), name='created_by'),
    path('category/<slug:slug>', Category.as_view(), name='category'),
    path('tag/<slug:slug>', Tag.as_view(), name='tag'),
    path('search/', Search.as_view(), name='search'),


]

djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),   
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root= settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from django.db import models
from utils.rands import slugify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse

class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
    
    name = models.CharField(max_length=255)
    slug = models.SlugField(
        max_length=255,unique=True,
        default=None,null=True,blank=True
    )

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)
    def __str__(self) -> str:
        return self.name

class Category(models.Model):
    class Meta:
        verbose_name = 'Catergory'
        verbose_name_plural = 'Categories'
    
    name = models.CharField(max_length=255)
    slug = models.SlugField(
        max_length=255,unique=True,
        default=None,null=True,blank=True
    )

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)
    def __str__(self) -> str:
        return self.name

class Page(models.Model):
    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'
    
    title = models.CharField(max_length=65)
    slug = models.SlugField(
        max_length=255,unique=True,
        default=None,null=True,blank=True
    )
    is_published = models.BooleanField(default=False)
    content = models.TextField()
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)
        return super().save(*args, **kwargs)
    def __str__(self) -> str:
        return self.title
    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))
    
class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-pk')

class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        
    objects = PostManager()
    
    title = models.CharField(max_length=65,)
    slug = models.SlugField(
        max_length=255,unique=True,
        default=None,null=True,blank=True
    )
    excerpt = models.CharField(max_length=150,)
    is_published = models.BooleanField(default=False)
    content = models.TextField()
    cover = models.ImageField(upload_to='posts/%Y/%m/', blank=True, default='')
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text=('Se marcado, exibirá a capa dentro do post')
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='page_created_by'
    )
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='page_updated_by'
        #o nome que chamamos a foreignkey
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,
    )
    tag = models.ManyToManyField(Tag, blank=True, default='')
    
    
    #muitos para muitos em ambas as direções, 1 post pode ter várias tags,
    # 1 tag pode ter vários posts
    #no sql seria uma terceira tabela fazendo a junção
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False
        
        if self.cover:
            cover_changed = current_cover_name != self.cover.name
        if cover_changed:
            resize_image(self.cover, 900, True, 90)

        return super_save
        
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))
    

class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            resize_image(self.file, 900, True, 70)

        return super_save

djangoapp/blog/views.py
from typing import Any
from django.core.paginator import Paginator
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from blog.models import Post, Page
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404, HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView 

PER_PAGE = 9
class Index(ListView):
    model = Post #nesse caso não precisa pois estamos passando uma queryset
    template_name = 'blog/pages/index.html'
    context_object_name = 'posts'
    ordering= '-pk',
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title': 'Home - '
        })
        return context
    
# def index(request):
#     posts = Post.objects.get_published()
    
#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#         }
#     )

class Page(DetailView):
    model = Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'
    
    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        page = self.get_object()
        context.update({
            'page_title': f'{page.title} - Página -'
        })
        return context

# def page(request, slug):
#     page = Page.objects.filter(is_published=True).filter(slug=slug).first()
#     if page is None:
#         raise Http404()
#     page_title = f'{page.title} - Página -'
#     return render(
#         request,
#         'blog/pages/page.html',
#         {
#             'page':page,
#             'page_title': page_title,
           
#         }
#     )

class Post(DetailView):
    model = Post
    template_name = 'blog/pages/post.html'
    slug_field = 'slug'
    context_object_name = 'post'
    
    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context.update({
            'page_title': f'{post.title} - Post -'
        })
        return context

# def post(request, slug):
#     post = Post.objects.get_published().filter(slug=slug).first()
#     if post is None:
#         raise Http404()
#     page_title = f'{post.title} - Post - '
#     return render(
#         request,
#         'blog/pages/post.html',
#         {
#             'post': post,
#             'page_title': page_title,

#         }
#     )

class Created_by(Index):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_context = {}
    
    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context['user'].pk)
        return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username
        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'
        page_title = user_full_name + ' posts - '
        ctx.update({
            'page_title' : page_title,
        })
        return ctx
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        author_id = self.kwargs.get('author_id')
        user = User.objects.filter(pk=author_id).first()
        if user is None:
            return redirect('blog:index')
        self._temp_context.update({
            'author_id': author_id,
            'user': user,
        })
        return super().get(request, *args, **kwargs)


# def created_by(request, author_id):
#     user = User.objects.filter(pk=author_id).first()
#     if user is None:
#         raise Http404()
#     posts = Post.objects.get_published().filter(created_by__pk=author_id)
#     user_full_name = user.username
#     if user.first_name:
#         user_full_name = f'{user.first_name} {user.last_name}'
#     page_title = user_full_name + ' posts - '
#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }
#     )

class Category(Index):
    allow_empty = False #levanta 404 se estiver vazio
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            category__slug=self.kwargs.get('slug')
        )
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title': f'{self.object_list[0].category.name} - Categoria - '
        })
        return context

# def category(request, slug):
#     posts = Post.objects.get_published().filter(category__slug=slug)
#                                         # __ buscando de foreign key do post
#     if len(posts) == 0:
#         raise Http404()
        
#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     page_title = f'{page_obj[0].category.name} - Categoria - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }
#     )

class Tag(Index):
    allow_empty = False #levanta 404 se estiver vazio
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            tag__slug=self.kwargs.get('slug')
        )
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title': f'{self.object_list[0].tag.first().name} - Tag - '
        })
        return context

# def tag(request, slug):
#     posts = Post.objects.get_published().filter(tag__slug=slug)
#                                         # __ buscando de foreign key do post
    
#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)
#     page_title = f'{page_obj[0].tag.first().name} - Tag - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,

#         }
#     )

class Search(Index):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._search_value = ''
        
    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self._search_value = request.GET.get('search').strip()

        return super().setup(request, *args, **kwargs)
    
    def get_queryset(self) -> QuerySet[Any]:
        search_value = self._search_value
        return super().get_queryset().filter(
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)   
        )[0:PER_PAGE]
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        search_value = self._search_value
        context.update({
            'page_title': f'{search_value[:30]} - Search -',
            'search_value': search_value,
        })
        return context
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if self._search_value == '':
            return redirect('blog:index')
        return super().get(request, *args, **kwargs)

# def search(request):
#     search_value = request.GET.get('search').strip()
#     posts = Post.objects.get_published().filter(
#         Q(title__icontains=search_value) |
#         Q(excerpt__icontains=search_value) |
#         Q(content__icontains=search_value)   
#     )[0:PER_PAGE]
#                                         # __ buscando de foreign key do post
#     page_title = f'{search_value[:30]} - Search -'

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': posts,
#             'search_value': search_value,
#              'page_title': page_title,
#         }
#     )

djangoapp/blog/templates/blog/pages/index.html
{% extends "../partials/base.html" %}


{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">
      
      {% if posts %}
        <div class="card-grid">
          {% for post in posts %}
            {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
          {% endfor %}
        </div>
        {% else %}
        <div>
          <h1> Nada encontrado </h1>
        </div>
        {% endif %}
      </div>
    </div>
  </main>


{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends "../partials/base.html" %}

{% block content %}


<main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center"> {{page.title}} </h1>
        {{page.content|safe}}
      </div>
    </div>
  </main>


{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends "../partials/base.html" %}

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}



{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
      <div class="single-post-cover pb-base">
        <img loading="lazy" src="{{post.cover.url}} " alt="{{post.title}}">
      </div>
      {% endif %}
      <h2 class="single-post-title pb-base center">
        {{post.title}}      
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url "blog:created_by" post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
              {{post.created_by.first_name}}
              {{post.created_by.last_name}}
              {% else %}
              {{post.created_by.username}}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link" >
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{post.created_at | date:'d/m/Y \à\s H:i' }}
            </span>
          </span>
        </div>

        {% if post.category %}
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url "blog:category" post.category.slug %}">
            <i class="fa-solid fa-tag"></i>
            <span>
              {{post.category}}
            </span>
          </a>
        </div>
        {% endif %}
      </div>

      <p class="single-post-excerpt pb-base">
        {{post.excerpt|safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{post.content|safe}}
        {% comment %} code mirror abaixo, tag PRE {% endcomment %}
        {% comment %} <pre data-language="python">def category(request, slug):
          posts = Post.objects.get_published().filter(category__slug=slug)
                                              # __ buscando de foreign key do post
          
          paginator = Paginator(posts, PER_PAGE)
          page_number = request.GET.get("page")
          page_obj = paginator.get_page(page_number)
      
          return render(
              request,
              'blog/pages/index.html',
              {
                  'page_obj': page_obj,
              }
          )</pre> {% endcomment %}
        
        {% if post.tag.exists %}
        <div class="post-tags">
          <span>Tags: </span>
          {% for tag in post.tag.all  %}
            <a class="post-tag-link" href="{% url "blog:tag" tag.slug %}">
              <i class="fa-solid fa-link"></i>
              <span> {{tag.name}} </span>
            </a> 
          {% endfor %}
        </div>
        {% endif %}
      </div>
    
    </div>
  </div>
</main>


{% endblock content %}